name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  deploy-frontend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: clone
        uses: actions/checkout@v4

      - name: install Vercel CLI
        run: npm install --global vercel@latest

      - name: pull Vercel environment info
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

      - name: build project
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

      - name: deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

  deploy-backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: clone
        uses: actions/checkout@v4

      - name: install Vercel CLI
        run: npm install --global vercel@latest

      - name: pull Vercel environment info
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./backend

      - name: build project
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./backend

      - name: deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./backend
